using System.Collections.Immutable;
using MyLittleContentEngine.Models;
using MyLittleContentEngine.Services.Content.TableOfContents;
using MyLittleContentEngine.Services.Generation;

namespace MyLittleContentEngine.Services.Content;

/// <summary>
/// A Content Service responsible for parsing and handling content. <see cref="ContentEngineOptions"/>.
/// </summary>
public interface IContentService
{
    /// <summary>
    /// Gets the search priority for this content service. Higher values appear first in search results.
    /// Default priority is 1. Recommended values: 1 (low), 5 (medium), 10 (high).
    /// </summary>
    int SearchPriority { get; }
    /// <summary>
    /// Gets the collection of pages that should be generated for this content.
    /// </summary>
    /// <returns>
    /// An ImmutableList of PageToGenerate objects, each representing a page that
    /// should be processed by the <see cref="OutputGenerationService"/>.
    /// </returns>
    Task<ImmutableList<PageToGenerate>> GetPagesToGenerateAsync();

    /// <summary>
    /// Gets the collection of Table of Contents entries with hierarchy parts for building navigation structure.
    /// This provides the content service with control over how entries are organized in the TOC hierarchy.
    /// </summary>
    /// <returns>
    /// An ImmutableList of ContentTocItem objects that define the hierarchical structure of the TOC.
    /// </returns>
    Task<ImmutableList<ContentTocItem>> GetContentTocEntriesAsync();

    /// <summary>
    /// Gets the collection of content that should be copied to the output directory.
    /// </summary>
    /// <returns>
    /// An ImmutableList of ContentToCopy objects, each representing a file or directory
    /// that should be copied by the <see cref="OutputGenerationService"/>.
    /// </returns>
    Task<ImmutableList<ContentToCopy>> GetContentToCopyAsync();

    /// <summary>
    /// Gets the cross-references used in the content system, such as those found in the Table of Contents (ToC) or xref links.
    /// </summary>
    /// <returns>
    /// An ImmutableList of CrossReference objects, each representing a cross-reference in the content system.
    /// </returns>
    public Task<ImmutableList<CrossReference>> GetCrossReferencesAsync();

    /// <summary>
    /// Gets the collection of content that should be created dynamically during generation.
    /// </summary>
    /// <returns>
    /// An ImmutableList of ContentToCreate objects, each representing content that
    /// should be generated by the <see cref="OutputGenerationService"/>.
    /// </returns>
    public Task<ImmutableList<ContentToCreate>> GetContentToCreateAsync()
    {
        return Task.FromResult(ImmutableList<ContentToCreate>.Empty);
    }
}