# configuration file for dotnet-releaser
[msbuild]
project = "MyLittleContentEngine.sln"
build_debug = true
[msbuild.properties]
DotNetReleaser = "true"
verbosity="d"
[test]
run_tests_for_debug = true
[nuget]
publish_draft = true # publish draft NuGet package per commit
[github]
user = "phil-scott-78"
repo = "MyLittleContentEngine"